In [54]:
import pandas as pd
import pymysql
from sqlalchemy import create_engine

#to confirm pandas installation
print(pd.__version__)

2.2.3

In [11]:
# Load the file 
df = pd.read_csv('Walmart.csv', encoding_errors='ignore' )
#to seek the total number of rows and columns
df.shape

(10051, 11)

In [12]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [13]:
df.describe()

         invoice_id      quantity        rating  profit_margin
count  10051.000000  10020.000000  10051.000000   10051.000000
mean    5025.741220      2.353493      5.825659       0.393791
std     2901.174372      1.602658      1.763991       0.090669
min        1.000000      1.000000      3.000000       0.180000
25%     2513.500000      1.000000      4.000000       0.330000
50%     5026.000000      2.000000      6.000000       0.330000
75%     7538.500000      3.000000      7.000000       0.480000
max    10000.000000     10.000000     10.000000       0.570000

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  object
 2   City            10051 non-null  object
 3   category        10051 non-null  object
 4   unit_price      10020 non-null  object
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  object
 7   time            10051 non-null  object
 8   payment_method  10051 non-null  object
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), object(7)
memory usage: 863.9+ KB

In [23]:
#check any duplicate
#df.duplicated().sum()
df.drop_duplicates(inplace=True)  #removed all duplicates

In [24]:
#to identify null
df.isnull().sum()

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

In [28]:
#dropping all rows with missing records
df.dropna(inplace=True)
#verify
df.isnull().sum()

invoice_id        0
Branch            0
City              0
category          0
unit_price        0
quantity          0
date              0
time              0
payment_method    0
rating            0
profit_margin     0
dtype: int64

In [29]:
df.shape

(9969, 11)

In [30]:
df.dtypes

invoice_id          int64
Branch             object
City               object
category           object
unit_price         object
quantity          float64
date               object
time               object
payment_method     object
rating            float64
profit_margin     float64
dtype: object

In [34]:
df['unit_price'] = df['unit_price'].str.replace('$', '').astype(float)
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9969 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      9969 non-null   int64
 1   Branch          9969 non-null   object
 2   City            9969 non-null   object
 3   category        9969 non-null   object
 4   unit_price      9969 non-null   float64
 5   quantity        9969 non-null   float64
 6   date            9969 non-null   object
 7   time            9969 non-null   object
 8   payment_method  9969 non-null   object
 9   rating          9969 non-null   float64
 10  profit_margin   9969 non-null   float64
dtypes: float64(4), int64(1), object(6)
memory usage: 934.6+ KB

In [64]:
df.columns=df.columns.str.lower() #to change lower case
df.columns

Index(['invoice_id', 'branch', 'city', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin', 'total'],
      dtype='object')

In [38]:
#to find total and create new comlumn 
df['total']=df['unit_price']*df['quantity']
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48,604.17

In [44]:
%pip install pymysql sqlalchemy

Note: you may need to restart the kernel to use updated packages.Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: sqlalchemy in c:\users\user\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\user\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\user\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0

In [61]:
import pymysql

# Connect local mysql server 
conn = pymysql.connect(host='localhost', user='root', password='root123')
cursor = conn.cursor()

# 1. Added the 'S' to EXISTS
cursor.execute("CREATE DATABASE IF NOT EXISTS walmart_db;")

# 2. Added the 'S' to DATABASES
cursor.execute("SHOW DATABASES;")
databases = [db[0] for db in cursor.fetchall()]

print("🎉 Successfully Connected! Your active databases are:")
print(databases)

cursor.close()
conn.close()

🎉 Successfully Connected! Your active databases are:
['information_schema', 'mysql', 'performance_schema', 'sakila', 'sys', 'walmart_db', 'world']

In [49]:
df.shape

(9969, 12)

In [50]:
df.to_csv('walmart_clean_data.csv', index=False)

In [51]:
help(df.to_sql)

Help on method to_sql in module pandas.core.generic:

to_sql(
    name: 'str',
    con,
    *,
    schema: 'str | None' = None,
    if_exists: "Literal['fail', 'replace', 'append']" = 'fail',
    index: 'bool_t' = True,
    index_label: 'IndexLabel | None' = None,
    chunksize: 'int | None' = None,
    dtype: 'DtypeArg | None' = None,
    method: "Literal['multi'] | Callable | None" = None
) -> 'int | None' method of pandas.core.frame.DataFrame instance
    Write records stored in a DataFrame to a SQL database.

    Databases supported by SQLAlchemy [1]_ are supported. Tables can be
    newly created, appended to, or overwritten.

    Parameters
    ----------
    name : str
        Name of SQL table.
    con : sqlalchemy.engine.(Engine or Connection) or sqlite3.Connection
        Using SQLAlchemy makes it possible to use any DB supported by that
        library. Legacy support is provided for sqlite3.Connection objects. The user
        is responsible for engine disposal and connection closure for the SQLAlchemy
        connectable. See `here                 <https://docs.sqlalchemy.org/en/20/core/connections.html>`_.
        If passing a sqlalchemy.engine.Connection which is already in a transaction,
        the transaction will not be committed.  If passing a sqlite3.Connection,
        it will not be possible to roll back the record insertion.

    schema : str, optional
        Specify the schema (if database flavor supports this). If None, use
        default schema.
    if_exists : {'fail', 'replace', 'append'}, default 'fail'
        How to behave if the table already exists.

        * fail: Raise a ValueError.
        * replace: Drop the table before inserting new values.
        * append: Insert new values to the existing table.

    index : bool, default True
        Write DataFrame index as a column. Uses `index_label` as the column
        name in the table. Creates a table index for this column.
    index_label : str or sequence, default None
        Column label for index column(s). If None is given (default) and
        `index` is True, then the index names are used.
        A sequence should be given if the DataFrame uses MultiIndex.
    chunksize : int, optional
        Specify the number of rows in each batch to be written at a time.
        By default, all rows will be written at once.
    dtype : dict or scalar, optional
        Specifying the datatype for columns. If a dictionary is used, the
        keys should be the column names and the values should be the
        SQLAlchemy types or strings for the sqlite3 legacy mode. If a
        scalar is provided, it will be applied to all columns.
    method : {None, 'multi', callable}, optional
        Controls the SQL insertion clause used:

        * None : Uses standard SQL ``INSERT`` clause (one per row).
        * 'multi': Pass multiple values in a single ``INSERT`` clause.
        * callable with signature ``(pd_table, conn, keys, data_iter)``.

        Details and a sample callable implementation can be found in the
        section :ref:`insert method <io.sql.method>`.

    Returns
    -------
    None or int
        Number of rows affected by to_sql. None is returned if the callable
        passed into ``method`` does not return an integer number of rows.

        The number of returned rows affected is the sum of the ``rowcount``
        attribute of ``sqlite3.Cursor`` or SQLAlchemy connectable which may not
        reflect the exact number of written rows as stipulated in the
        `sqlite3 <https://docs.python.org/3/library/sqlite3.html#sqlite3.Cursor.rowcount>`__ or
        `SQLAlchemy <https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.CursorResult.rowcount>`__.

        .. versionadded:: 1.4.0

    Raises
    ------
    ValueError
        When the table already exists and `if_exists` is 'fail' (the
        default).

    See Also
    --------
    read_sql : Read a DataFrame from a table.

    Notes
    -----
    Timezone aware datetime columns will be written as
    ``Timestamp with timezone`` type with SQLAlchemy if supported by the
    database. Otherwise, the datetimes will be stored as timezone unaware
    timestamps local to the original timezone.

    Not all datastores support ``method="multi"``. Oracle, for example,
    does not support multi-value insert.

    References
    ----------
    .. [1] https://docs.sqlalchemy.org
    .. [2] https://www.python.org/dev/peps/pep-0249/

    Examples
    --------
    Create an in-memory SQLite database.

    >>> from sqlalchemy import create_engine
    >>> engine = create_engine('sqlite://', echo=False)

    Create a table from scratch with 3 rows.

    >>> df = pd.DataFrame({'name' : ['User 1', 'User 2', 'User 3']})
    >>> df
         name
    0  User 1
    1  User 2
    2  User 3

    >>> df.to_sql(name='users', con=engine)
    3
    >>> from sqlalchemy import text
    >>> with engine.connect() as conn:
    ...    conn.execute(text("SELECT * FROM users")).fetchall()
    [(0, 'User 1'), (1, 'User 2'), (2, 'User 3')]

    An `sqlalchemy.engine.Connection` can also be passed to `con`:

    >>> with engine.begin() as connection:
    ...     df1 = pd.DataFrame({'name' : ['User 4', 'User 5']})
    ...     df1.to_sql(name='users', con=connection, if_exists='append')
    2

    This is allowed to support operations that require that the same
    DBAPI connection is used for the entire operation.

    >>> df2 = pd.DataFrame({'name' : ['User 6', 'User 7']})
    >>> df2.to_sql(name='users', con=engine, if_exists='append')
    2
    >>> with engine.connect() as conn:
    ...    conn.execute(text("SELECT * FROM users")).fetchall()
    [(0, 'User 1'), (1, 'User 2'), (2, 'User 3'),
     (0, 'User 4'), (1, 'User 5'), (0, 'User 6'),
     (1, 'User 7')]

    Overwrite the table with just ``df2``.

    >>> df2.to_sql(name='users', con=engine, if_exists='replace',
    ...            index_label='id')
    2
    >>> with engine.connect() as conn:
    ...    conn.execute(text("SELECT * FROM users")).fetchall()
    [(0, 'User 6'), (1, 'User 7')]

    Use ``method`` to define a callable insertion method to do nothing
    if there's a primary key conflict on a table in a PostgreSQL database.

    >>> from sqlalchemy.dialects.postgresql import insert
    >>> def insert_on_conflict_nothing(table, conn, keys, data_iter):
    ...     # "a" is the primary key in "conflict_table"
    ...     data = [dict(zip(keys, row)) for row in data_iter]
    ...     stmt = insert(table.table).values(data).on_conflict_do_nothing(index_elements=["a"])
    ...     result = conn.execute(stmt)
    ...     return result.rowcount
    >>> df_conflict.to_sql(name="conflict_table", con=conn, if_exists="append", method=insert_on_conflict_nothing)  # doctest: +SKIP
    0

    For MySQL, a callable to update columns ``b`` and ``c`` if there's a conflict
    on a primary key.

    >>> from sqlalchemy.dialects.mysql import insert
    >>> def insert_on_conflict_update(table, conn, keys, data_iter):
    ...     # update columns "b" and "c" on primary key conflict
    ...     data = [dict(zip(keys, row)) for row in data_iter]
    ...     stmt = (
    ...         insert(table.table)
    ...         .values(data)
    ...     )
    ...     stmt = stmt.on_duplicate_key_update(b=stmt.inserted.b, c=stmt.inserted.c)
    ...     result = conn.execute(stmt)
    ...     return result.rowcount
    >>> df_conflict.to_sql(name="conflict_table", con=conn, if_exists="append", method=insert_on_conflict_update)  # doctest: +SKIP
    2

    Specify the dtype (especially useful for integers with missing values).
    Notice that while pandas is forced to store the data as floating point,
    the database supports nullable integers. When fetching the data with
    Python, we get back integer scalars.

    >>> df = pd.DataFrame({"A": [1, None, 2]})
    >>> df
         A
    0  1.0
    1  NaN
    2  2.0

    >>> from sqlalchemy.types import Integer
    >>> df.to_sql(name='integers', con=engine, index=False,
    ...           dtype={"A": Integer()})
    3

    >>> with engine.connect() as conn:
    ...   conn.execute(text("SELECT * FROM integers")).fetchall()
    [(1,), (None,), (2,)]

In [58]:
#mysql connection
engine_mysql = create_engine("mysql+pymysql://root:root123@localhost:3306/walmart_db")
try: 
    engine_mysql
    print("connection success to my sql")
except: 
    print("unable to connect")

connection success to my sql

In [65]:
df.to_sql(name='walmart',con=engine_mysql, if_exists='append', index=False)

9969

In [66]:
df.shape

(9969, 12)